2015-09-14 14:27:24 开始运行爬虫----------paipaidai3---------------------------------------
2015-09-14 14:27:26+0800 [scrapy] INFO: Scrapy 0.24.4 started (bot: paipaidai)
2015-09-14 14:27:26+0800 [scrapy] INFO: Optional features available: ssl, http11, boto, django
2015-09-14 14:27:26+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'paipaidai.spiders', 'SPIDER_MODULES': ['paipaidai.spiders'], 'BOT_NAME': 'paipaidai'}
2015-09-14 14:27:26+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2015-09-14 14:27:27+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-09-14 14:27:27+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-09-14 14:27:27+0800 [scrapy] INFO: Enabled item pipelines: PaipaidaiPipeline
2015-09-14 14:27:27+0800 [paipaidai3] INFO: Spider opened
2015-09-14 14:27:27+0800 [paipaidai3] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-09-14 14:27:27+0800 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6031
2015-09-14 14:27:27+0800 [scrapy] DEBUG: Web service listening on 127.0.0.1:6088
2015-09-14 14:27:31+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/12_s0_p5>
2015-09-14 14:27:33+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/12_s0_p6>
2015-09-14 14:27:34+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/13_s0_p6> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:36+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/13_s0_p5>
2015-09-14 14:27:37+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/14_s0_p5> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:39+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/14_s0_p6> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:47+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/8_s0_p5>
2015-09-14 14:27:49+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/8_s0_p6>
2015-09-14 14:27:49+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/3_s0_p6> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:51+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/3_s0_p5>
2015-09-14 14:27:54+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/15_s0_p6> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:57+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/15_s0_p5>
2015-09-14 14:27:59+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/16_s0_p6> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:01+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/16_s0_p5>
2015-09-14 14:28:02+0800 [paipaidai3] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:05+0800 [paipaidai3] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:08+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/13_s0_p6> (failed 2 times): 503 Service Unavailable
2015-09-14 14:28:10+0800 [paipaidai3] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:13+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/14_s0_p5> (failed 2 times): 503 Service Unavailable
2015-09-14 14:28:19+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/14_s0_p6>
2015-09-14 14:28:20+0800 [paipaidai3] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:22+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:27+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/3_s0_p6>
2015-09-14 14:28:27+0800 [paipaidai3] INFO: Crawled 1 pages (at 1 pages/min), scraped 0 items (at 0 items/min)
2015-09-14 14:28:28+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/15_s0_p6> (failed 2 times): 503 Service Unavailable
2015-09-14 14:28:30+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:30+0800 [paipaidai3] DEBUG: Filtered duplicate request: <GET http://www.ppdai.com/list/4182242> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2015-09-14 14:28:30+0800 [paipaidai3] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:32+0800 [paipaidai3] DEBUG: Retrying <GET http://www.ppdai.com/lend/16_s0_p6> (failed 2 times): 503 Service Unavailable
2015-09-14 14:28:35+0800 [paipaidai3] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:43+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:43+0800 [paipaidai3] DEBUG: Gave up retrying <GET http://www.ppdai.com/lend/13_s0_p6> (failed 3 times): 503 Service Unavailable
2015-09-14 14:28:43+0800 [paipaidai3] DEBUG: Crawled (503) <GET http://www.ppdai.com/lend/13_s0_p6> (referer: None)
2015-09-14 14:28:43+0800 [paipaidai3] DEBUG: Ignoring response <503 http://www.ppdai.com/lend/13_s0_p6>: HTTP status code is not handled or not allowed
2015-09-14 14:28:46+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:51+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:52+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/14_s0_p5>
2015-09-14 14:28:54+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:55+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4182242> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:55+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4182242>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:56+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:59+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4124938> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:59+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4124938>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:00+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4124481> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:00+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4124481>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:05+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:05+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4215152> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:05+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4215152>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:08+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4186674> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:08+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4186674>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:10+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4185554> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:10+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4185554>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:12+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:15+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4222360> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:15+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4222360>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:17+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:17+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/3919008> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:17+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/3919008>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:19+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4225589> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:19+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4225589>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:22+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4006181> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:22+0800 [paipaidai3] ERROR: Spider error processing <GET http://www.ppdai.com/list/4006181>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base3.py", line 56, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:27+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:27+0800 [paipaidai3] INFO: Crawled 22 pages (at 21 pages/min), scraped 0 items (at 0 items/min)
2015-09-14 14:29:30+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/16_s0_p6>
2015-09-14 14:29:33+0800 [paipaidai3] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/15_s0_p6>
2015-09-14 14:29:36+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:39+0800 [paipaidai3] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:39+0800 [paipaidai3] INFO: Closing spider (finished)
2015-09-14 14:29:39+0800 [paipaidai3] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 13631,
	 'downloader/request_count': 53,
	 'downloader/request_method_count/GET': 53,
	 'downloader/response_bytes': 216114,
	 'downloader/response_count': 53,
	 'downloader/response_status_count/200': 23,
	 'downloader/response_status_count/302': 13,
	 'downloader/response_status_count/503': 17,
	 'dupefilter/filtered': 120,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 9, 14, 6, 29, 39, 198796),
	 'log_count/DEBUG': 58,
	 'log_count/ERROR': 10,
	 'log_count/INFO': 9,
	 'request_depth_max': 1,
	 'response_received_count': 24,
	 'scheduler/dequeued': 53,
	 'scheduler/dequeued/memory': 53,
	 'scheduler/enqueued': 53,
	 'scheduler/enqueued/memory': 53,
	 'spider_exceptions/IndexError': 10,
	 'start_time': datetime.datetime(2015, 9, 14, 6, 27, 27, 787672)}
2015-09-14 14:29:39+0800 [paipaidai3] INFO: Spider closed (finished)
2015-09-14 14:29:49 爬取结束-------------paipaidai3---------------------------------------
