2015-09-15 10:53:22 开始运行爬虫----------lujinsuo---------------------------------------
2015-09-15 10:53:34+0800 [scrapy] INFO: Scrapy 0.24.4 started (bot: lujinsuo)
2015-09-15 10:53:34+0800 [scrapy] INFO: Optional features available: ssl, http11, boto, django
2015-09-15 10:53:34+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'lujinsuo.spiders', 'SPIDER_MODULES': ['lujinsuo.spiders'], 'BOT_NAME': 'lujinsuo'}
2015-09-15 10:53:34+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2015-09-15 10:53:35+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-09-15 10:53:35+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-09-15 10:53:35+0800 [scrapy] INFO: Enabled item pipelines: LujinsuoPipeline
2015-09-15 10:53:35+0800 [lujinsuo] INFO: Spider opened
2015-09-15 10:53:35+0800 [lujinsuo] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:53:35+0800 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6043
2015-09-15 10:53:35+0800 [scrapy] DEBUG: Web service listening on 127.0.0.1:6100
2015-09-15 10:53:37+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236749> from <GET https://list.lufax.com/list/productDetail?productId=236749>
2015-09-15 10:53:40+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236907> from <GET https://list.lufax.com/list/productDetail?productId=236907>
2015-09-15 10:53:44+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=237498> from <GET https://list.lufax.com/list/productDetail?productId=237498>
2015-09-15 10:53:48+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236226> from <GET https://list.lufax.com/list/productDetail?productId=236226>
2015-09-15 10:53:51+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236662> from <GET https://list.lufax.com/list/productDetail?productId=236662>
2015-09-15 10:53:55+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236517> from <GET https://list.lufax.com/list/productDetail?productId=236517>
2015-09-15 10:53:59+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=237458> from <GET https://list.lufax.com/list/productDetail?productId=237458>
2015-09-15 10:54:04+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236518> from <GET https://list.lufax.com/list/productDetail?productId=236518>
2015-09-15 10:54:08+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=237512> from <GET https://list.lufax.com/list/productDetail?productId=237512>
2015-09-15 10:54:12+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236600> from <GET https://list.lufax.com/list/productDetail?productId=236600>
2015-09-15 10:54:16+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236917> from <GET https://list.lufax.com/list/productDetail?productId=236917>
2015-09-15 10:54:19+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236914> from <GET https://list.lufax.com/list/productDetail?productId=236914>
2015-09-15 10:54:23+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236494> from <GET https://list.lufax.com/list/productDetail?productId=236494>
2015-09-15 10:54:26+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236495> from <GET https://list.lufax.com/list/productDetail?productId=236495>
2015-09-15 10:54:30+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=237455> from <GET https://list.lufax.com/list/productDetail?productId=237455>
2015-09-15 10:54:35+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=237489> from <GET https://list.lufax.com/list/productDetail?productId=237489>
2015-09-15 10:54:35+0800 [lujinsuo] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:54:38+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236749> (referer: None)
2015-09-15 10:54:38+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236749>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:43+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236907> (referer: None)
2015-09-15 10:54:43+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236907>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:47+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET http://www.lu.com/notFound.html> from <GET https://list.lu.com/list/productDetail?productId=237498>
2015-09-15 10:54:50+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236226> (referer: None)
2015-09-15 10:54:50+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236226>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:54+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236662> (referer: None)
2015-09-15 10:54:54+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236662>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:57+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET http://www.lu.com/notFound.html> from <GET https://list.lu.com/list/productDetail?productId=236517>
2015-09-15 10:55:01+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=237458> (referer: None)
2015-09-15 10:55:01+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=237458>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:03+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236518> (referer: None)
2015-09-15 10:55:03+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236518>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:07+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=237512> (referer: None)
2015-09-15 10:55:07+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=237512>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:09+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236600> (referer: None)
2015-09-15 10:55:09+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236600>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:12+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236917> (referer: None)
2015-09-15 10:55:12+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236917>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:15+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236914> (referer: None)
2015-09-15 10:55:15+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236914>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:17+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET http://www.lu.com/notFound.html> from <GET https://list.lu.com/list/productDetail?productId=236494>
2015-09-15 10:55:21+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET http://www.lu.com/notFound.html> from <GET https://list.lu.com/list/productDetail?productId=236495>
2015-09-15 10:55:24+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=237455> (referer: None)
2015-09-15 10:55:24+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=237455>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:28+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=237489> (referer: None)
2015-09-15 10:55:28+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=237489>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:32+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236116> from <GET https://list.lufax.com/list/productDetail?productId=236116>
2015-09-15 10:55:35+0800 [lujinsuo] INFO: Crawled 12 pages (at 12 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:55:36+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236711> from <GET https://list.lufax.com/list/productDetail?productId=236711>
2015-09-15 10:55:41+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://www.lu.com/notFound.html> from <GET http://www.lu.com/notFound.html>
2015-09-15 10:55:45+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236854> from <GET https://list.lufax.com/list/productDetail?productId=236854>
2015-09-15 10:55:49+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236617> from <GET https://list.lufax.com/list/productDetail?productId=236617>
2015-09-15 10:55:53+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://www.lu.com/notFound.html> from <GET http://www.lu.com/notFound.html>
2015-09-15 10:55:57+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=237341> from <GET https://list.lufax.com/list/productDetail?productId=237341>
2015-09-15 10:56:01+0800 [lujinsuo] DEBUG: Redirecting (301) to <GET https://list.lu.com/list/productDetail?productId=236631> from <GET https://list.lufax.com/list/productDetail?productId=236631>
2015-09-15 10:56:05+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://www.lu.com/notFound.html> from <GET http://www.lu.com/notFound.html>
2015-09-15 10:56:10+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://www.lu.com/notFound.html> from <GET http://www.lu.com/notFound.html>
2015-09-15 10:56:14+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236116> (referer: None)
2015-09-15 10:56:14+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236116>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:56:17+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236711> (referer: None)
2015-09-15 10:56:17+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236711>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:56:21+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://promo.lu.com/transfer/v1/notFound.html> from <GET https://www.lu.com/notFound.html>
2015-09-15 10:56:24+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=236854> (referer: None)
2015-09-15 10:56:24+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=236854>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:56:27+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET http://www.lu.com/notFound.html> from <GET https://list.lu.com/list/productDetail?productId=236617>
2015-09-15 10:56:30+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://promo.lu.com/transfer/v1/notFound.html> from <GET https://www.lu.com/notFound.html>
2015-09-15 10:56:35+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://list.lu.com/list/productDetail?productId=237341> (referer: None)
2015-09-15 10:56:35+0800 [lujinsuo] ERROR: Spider error processing <GET https://list.lu.com/list/productDetail?productId=237341>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:56:35+0800 [lujinsuo] INFO: Crawled 16 pages (at 4 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:56:38+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET http://www.lu.com/notFound.html> from <GET https://list.lu.com/list/productDetail?productId=236631>
2015-09-15 10:56:42+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://promo.lu.com/transfer/v1/notFound.html> from <GET https://www.lu.com/notFound.html>
2015-09-15 10:56:46+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://promo.lu.com/transfer/v1/notFound.html> from <GET https://www.lu.com/notFound.html>
2015-09-15 10:56:49+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://promo.lu.com/transfer/v1/notFound.html> (referer: None)
2015-09-15 10:56:49+0800 [lujinsuo] ERROR: Spider error processing <GET https://promo.lu.com/transfer/v1/notFound.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:56:51+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://www.lu.com/notFound.html> from <GET http://www.lu.com/notFound.html>
2015-09-15 10:56:55+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://promo.lu.com/transfer/v1/notFound.html> (referer: None)
2015-09-15 10:56:55+0800 [lujinsuo] ERROR: Spider error processing <GET https://promo.lu.com/transfer/v1/notFound.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:56:59+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://www.lu.com/notFound.html> from <GET http://www.lu.com/notFound.html>
2015-09-15 10:57:02+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://promo.lu.com/transfer/v1/notFound.html> (referer: None)
2015-09-15 10:57:02+0800 [lujinsuo] ERROR: Spider error processing <GET https://promo.lu.com/transfer/v1/notFound.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:57:05+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://promo.lu.com/transfer/v1/notFound.html> (referer: None)
2015-09-15 10:57:05+0800 [lujinsuo] ERROR: Spider error processing <GET https://promo.lu.com/transfer/v1/notFound.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:57:08+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://promo.lu.com/transfer/v1/notFound.html> from <GET https://www.lu.com/notFound.html>
2015-09-15 10:57:12+0800 [lujinsuo] DEBUG: Redirecting (302) to <GET https://promo.lu.com/transfer/v1/notFound.html> from <GET https://www.lu.com/notFound.html>
2015-09-15 10:57:16+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://promo.lu.com/transfer/v1/notFound.html> (referer: None)
2015-09-15 10:57:16+0800 [lujinsuo] ERROR: Spider error processing <GET https://promo.lu.com/transfer/v1/notFound.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:57:21+0800 [lujinsuo] DEBUG: Crawled (200) <GET https://promo.lu.com/transfer/v1/notFound.html> (referer: None)
2015-09-15 10:57:21+0800 [lujinsuo] ERROR: Spider error processing <GET https://promo.lu.com/transfer/v1/notFound.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/lujinsuo/lujinsuo/spiders/base.py", line 60, in parse
	    amount = sel.xpath('//ul[@class=\"clearfix detail-info-list\"]/li/p/strong/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:57:21+0800 [lujinsuo] INFO: Closing spider (finished)
2015-09-15 10:57:21+0800 [lujinsuo] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 14926,
	 'downloader/request_count': 62,
	 'downloader/request_method_count/GET': 62,
	 'downloader/response_bytes': 678032,
	 'downloader/response_count': 62,
	 'downloader/response_status_count/200': 22,
	 'downloader/response_status_count/301': 22,
	 'downloader/response_status_count/302': 18,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 9, 15, 2, 57, 21, 131679),
	 'log_count/DEBUG': 64,
	 'log_count/ERROR': 22,
	 'log_count/INFO': 10,
	 'response_received_count': 22,
	 'scheduler/dequeued': 62,
	 'scheduler/dequeued/memory': 62,
	 'scheduler/enqueued': 62,
	 'scheduler/enqueued/memory': 62,
	 'spider_exceptions/IndexError': 22,
	 'start_time': datetime.datetime(2015, 9, 15, 2, 53, 35, 976211)}
2015-09-15 10:57:21+0800 [lujinsuo] INFO: Spider closed (finished)
2015-09-15 10:57:31 爬取结束-------------lujinsuo---------------------------------------
